//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.32
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace GuardRecord.Entities {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "failed_jobs")]
	public partial class FailedJobs {

		[JsonProperty, Column(Name = "id", DbType = "bigint unsigned", IsPrimary = true, IsIdentity = true)]
		public ulong Id { get; set; }

		[JsonProperty, Column(Name = "connection", DbType = "text")]
		public string Connection { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "exception", DbType = "longtext")]
		public string Exception { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "failed_at", DbType = "timestamp")]
		public DateTime FailedAt { get; set; }

		[JsonProperty, Column(Name = "payload", DbType = "longtext")]
		public string Payload { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "queue", DbType = "text")]
		public string Queue { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "uuid")]
		public string Uuid { get; set; } = string.Empty;

	}

}
