//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.32
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;

namespace GuardRecord.Entities {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "guard_histories")]
	public partial class GuardHistories {

		[JsonProperty, Column(Name = "id", DbType = "bigint unsigned", IsPrimary = true, IsIdentity = true)]
		public ulong Id { get; set; }

		[JsonProperty, Column(Name = "created_at", DbType = "timestamp")]
		public DateTime? CreatedAt { get; set; }

		[JsonProperty, Column(Name = "is_deleted", DbType = "tinyint(1)")]
		public sbyte IsDeleted { get; set; }

		/// <summary>
		/// 等级
		/// </summary>
		[JsonProperty, Column(Name = "level")]
		public GuardHistoriesLEVEL Level { get; set; }

		/// <summary>
		/// 开通月数
		/// </summary>
		[JsonProperty, Column(Name = "num", DbType = "int")]
		public int Num { get; set; }

		/// <summary>
		/// 房间Id
		/// </summary>
		[JsonProperty, Column(Name = "room_id", DbType = "bigint unsigned")]
		public ulong RoomId { get; set; }

		[JsonProperty, Column(Name = "updated_at", DbType = "timestamp")]
		public DateTime? UpdatedAt { get; set; }

		/// <summary>
		/// 用户Id
		/// </summary>
		[JsonProperty, Column(Name = "user_id")]
		public string UserId { get; set; } = string.Empty;

		/// <summary>
		/// 用户名
		/// </summary>
		[JsonProperty, Column(Name = "username")]
		public string Username { get; set; } = string.Empty;

	}

	public enum GuardHistoriesLEVEL {
		/// <summary>
/// 3
/// </summary>
[Description("3")]
Unknow1 = 1, 
/// <summary>
/// 2
/// </summary>
[Description("2")]
Unknow2, 
/// <summary>
/// 1
/// </summary>
[Description("1")]
Unknow3
	}
}
