//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.32
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace GuardRecord.Entities {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "personal_access_tokens")]
	public partial class PersonalAccessTokens {

		[JsonProperty, Column(Name = "id", DbType = "bigint unsigned", IsPrimary = true, IsIdentity = true)]
		public ulong Id { get; set; }

		[JsonProperty, Column(Name = "abilities", DbType = "text")]
		public string Abilities { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "created_at", DbType = "timestamp")]
		public DateTime? CreatedAt { get; set; }

		[JsonProperty, Column(Name = "expires_at", DbType = "timestamp")]
		public DateTime? ExpiresAt { get; set; }

		[JsonProperty, Column(Name = "last_used_at", DbType = "timestamp")]
		public DateTime? LastUsedAt { get; set; }

		[JsonProperty, Column(Name = "name")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "token", DbType = "varchar(64)")]
		public string Token { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "tokenable_id", DbType = "bigint unsigned")]
		public ulong TokenableId { get; set; }

		[JsonProperty, Column(Name = "tokenable_type")]
		public string TokenableType { get; set; } = string.Empty;

		[JsonProperty, Column(Name = "updated_at", DbType = "timestamp")]
		public DateTime? UpdatedAt { get; set; }

	}

}
